name: Auto Version + ZIP

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Configurar Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Incrementar versão
        id: version
        run: |
          if [ -f version.txt ]; then
            VERSION=$(cat version.txt)
          else
            VERSION="1.0"
          fi

          echo "Versão atual: $VERSION"

          # Incremento +0.1
          NEW_VERSION=$(awk "BEGIN {printf \"%.1f\", $VERSION + 0.1}")

          echo "Nova versão: $NEW_VERSION"

          echo $NEW_VERSION > version.txt

          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit da nova versão
        run: |
          git add version.txt
          git commit -m "🔖 bump version to ${{ steps.version.outputs.version }}" || echo "Nada pra commitar"
          git push

      - name: Criar ZIP
        run: |
          zip -r mmdmigtools-${{ steps.version.outputs.version }}.zip . -x "*.git*" "*.github*"

      - name: Upload do ZIP
        uses: actions/upload-artifact@v4
        with:
          name: mmdmigtools-${{ steps.version.outputs.version }}
          path: mmdmigtools-${{ steps.version.outputs.version }}.zip
